var html_tags = {
    "!--...--": "<!--...-->\nDefines a comment",
    "!DOCTYPE": "<!DOCTYPE> \nDefines the document type",
    "a": "<a>\nDefines a hyperlink",
    "abbr": "<abbr>\nDefines an abbreviation or an acronym",
    "acronym": "<acronym>\nNot supported in HTML5. Use <abbr> instead.\nDefines an acronym",
    "address": "<address>\nDefines contact information for the author/owner of a document",
    "applet": "<applet>\nNot supported in HTML5. Use <embed> or <object> instead.\nDefines an embedded applet",
    "area": "<area>\nDefines an area inside an image-map",
    "article": "<article>\nDefines an article",
    "aside": "<aside>\nDefines content aside from the page content",
    "audio": "<audio>\nDefines sound content",
    "b": "<b>\nDefines bold text",
    "base": "<base>\nSpecifies the base URL/target for all relative URLs in a document",
    "basefont": "<basefont>\nNot supported in HTML5. Use CSS instead.\nSpecifies a default color, size, and font for all text in a document",
    "bdi": "<bdi>\nIsolates a part of text that might be formatted in a different direction from other text outside it",
    "bdo": "<bdo>\nOverrides the current text direction",
    "big": "<big>\nNot supported in HTML5. Use CSS instead.\nDefines big text",
    "blockquote": "<blockquote>\nDefines a section that is quoted from another source",
    "body": "<body>\nDefines the document's body",
    "br": "<br>\nDefines a single line break",
    "button": "<button>\nDefines a clickable button",
    "canvas": "<canvas>\nUsed to draw graphics, on the fly, via scripting (usually JavaScript)",
    "caption": "<caption>\nDefines a table caption",
    "center": "<center>\nNot supported in HTML5. Use CSS instead.\nDefines centered text",
    "cite": "<cite>\nDefines the title of a work",
    "code": "<code>\nDefines a piece of computer code",
    "col": "<col>\nSpecifies column properties for each column within a <colgroup> element ",
    "colgroup": "<colgroup>\nSpecifies a group of one or more columns in a table for formatting",
    "datalist": "<datalist>\nSpecifies a list of pre-defined options for input controls",
    "dd": "<dd>\nDefines a description/value of a term in a description list",
    "del": "<del>\nDefines text that has been deleted from a document",
    "details": "<details>\nDefines additional details that the user can view or hide",
    "dfn": "<dfn>\nRepresents the defining instance of a term",
    "dialog": "<dialog>\nDefines a dialog box or window",
    "dir": "<dir>\nNot supported in HTML5. Use <ul> instead.\nDefines a directory list",
    "div": "<div>\nDefines a section in a document",
    "dl": "<dl>\nDefines a description list",
    "dt": "<dt>\nDefines a term/name in a description list",
    "em": "<em>\nDefines emphasized text ",
    "embed": "<embed>\nDefines a container for an external (non-HTML) application",
    "fieldset": "<fieldset>\nGroups related elements in a form",
    "figcaption": "<figcaption>\nDefines a caption for a <figure> element",
    "figure": "<figure>\nSpecifies self-contained content",
    "font": "<font>\nNot supported in HTML5. Use CSS instead.\nDefines font, color, and size for text",
    "footer": "<footer>\nDefines a footer for a document or section",
    "form": "<form>\nDefines an HTML form for user input",
    "frame": "<frame>\nNot supported in HTML5.\nDefines a window (a frame) in a frameset",
    "frameset": "<frameset>\nNot supported in HTML5.\nDefines a set of frames",
    "h1 to <h6>": "<h1> to <h6>\nDefines HTML headings",
    "head": "<head>\nDefines information about the document",
    "header": "<header>\nDefines a header for a document or section",
    "hr": "<hr>\nDefines a thematic change in the content",
    "html": "<html>\nDefines the root of an HTML document",
    "i": "<i>\nDefines a part of text in an alternate voice or mood",
    "iframe": "<iframe>\nDefines an inline frame",
    "img": "<img>\nDefines an image",
    "input": "<input>\nDefines an input control",
    "ins": "<ins>\nDefines a text that has been inserted into a document",
    "kbd": "<kbd>\nDefines keyboard input",
    "keygen": "<keygen>\nDefines a key-pair generator field (for forms)",
    "label": "<label>\nDefines a label for an <input> element",
    "legend": "<legend>\nDefines a caption for a <fieldset> element",
    "li": "<li>\nDefines a list item",
    "link": "<link>\nDefines the relationship between a document and an external resource (most used to link to style sheets)",
    "main": "<main>\nSpecifies the main content of a document",
    "map": "<map>\nDefines a client-side image-map",
    "mark": "<mark>\nDefines marked/highlighted text",
    "menu": "<menu>\nDefines a list/menu of commands",
    "menuitem": "<menuitem>\nDefines a command/menu item that the user can invoke from a popup menu",
    "meta": "<meta>\nDefines metadata about an HTML document",
    "meter": "<meter>\nDefines a scalar measurement within a known range (a gauge)",
    "nav": "<nav>\nDefines navigation links",
    "noframes": "<noframes>\nNot supported in HTML5.\nDefines an alternate content for users that do not support frames",
    "noscript": "<noscript>\nDefines an alternate content for users that do not support client-side scripts",
    "object": "<object>\nDefines an embedded object",
    "ol": "<ol>\nDefines an ordered list",
    "optgroup": "<optgroup>\nDefines a group of related options in a drop-down list",
    "option": "<option>\nDefines an option in a drop-down list",
    "output": "<output>\nDefines the result of a calculation",
    "p": "<p>\nDefines a paragraph",
    "param": "<param>\nDefines a parameter for an object",
    "picture": "<picture>\nDefines a container for multiple image resources",
    "pre": "<pre>\nDefines preformatted text",
    "progress": "<progress>\nRepresents the progress of a task",
    "q": "<q>\nDefines a short quotation",
    "rp": "<rp>\nDefines what to show in browsers that do not support ruby annotations",
    "rt": "<rt>\nDefines an explanation/pronunciation of characters (for East Asian typography)",
    "ruby": "<ruby>\nDefines a ruby annotation (for East Asian typography)",
    "s": "<s>\nDefines text that is no longer correct",
    "samp": "<samp>\nDefines sample output from a computer program",
    "script": "<script>\nDefines a client-side script",
    "section": "<section>\nDefines a section in a document",
    "select": "<select>\nDefines a drop-down list",
    "small": "<small>\nDefines smaller text",
    "source": "<source>\nDefines multiple media resources for media elements (<video> and <audio>)",
    "span": "<span>\nDefines a section in a document",
    "strike": "<strike>\nNot supported in HTML5. Use <del> or <s> instead.\nDefines strikethrough text",
    "strong": "<strong>\nDefines important text",
    "style": "<style>\nDefines style information for a document",
    "sub": "<sub>\nDefines subscripted text",
    "summary": "<summary>\nDefines a visible heading for a <details> element",
    "sup": "<sup>\nDefines superscripted text",
    "table": "<table>\nDefines a table",
    "tbody": "<tbody>\nGroups the body content in a table",
    "td": "<td>\nDefines a cell in a table",
    "textarea": "<textarea>\nDefines a multiline input control (text area)",
    "tfoot": "<tfoot>\nGroups the footer content in a table",
    "th": "<th>\nDefines a header cell in a table",
    "thead": "<thead>\nGroups the header content in a table",
    "time": "<time>\nDefines a date/time",
    "title": "<title>\nDefines a title for the document",
    "tr": "<tr>\nDefines a row in a table",
    "track": "<track>\nDefines text tracks for media elements (<video> and <audio>)",
    "tt": "<tt>\nNot supported in HTML5. Use CSS instead.\nDefines teletype text",
    "u": "<u>\nDefines text that should be stylistically different from normal text",
    "ul": "<ul>\nDefines an unordered list",
    "var": "<var>\nDefines a variable",
    "video": "<video>\nDefines a video or movie",
    "wbr": "<wbr>\nDefines a possible line-break"
}